### ISSUE TITLE
권한처리 방법입니다.

### ISSUE THREAD

**Issue by joonseokhu** [wecode-bootcamp-korea/class101-backend#13]
pr 보다가 로그인한 사용자만 특정 라우트에 접근할수 있게 하는걸 하시려는것 같아서
간단하게 설명을 써놨습니다~

이미 할줄 아신다면 안보셔도 되지만, 필요하시다면 도움이 되셨으면 좋겠습니다!

https://gist.github.com/vraimentres/ad134d18dd18b136ffe404142b40f823

**Comment by onikss793** [comment]
감사합니다!!
